### ISSUE TITLE
Provide the ability to "diff" versions

### ISSUE THREAD

**Issue by TheSnoozer** [joodicator/mc-dev-data#2]
I'm not sure if it's a lack of understanding the different command line options, but for me there currently doesn't seem to be an option to "simply" generate a "diff" between two version.

Essentially what I'm interested in when generating such diff is what packets have changed (including the packet id) and what packets have been introduced.

Example use-case:
I have a client that has 1.12.2 (protocol 340) implemented and I want to find out what packets I need to change / alter / add in order to support 1.13 (protocol 393). I don't care about a support for any version in-between.

Should be achievable by simply filtering the ``versions`` in ``matrix_html``.
E.g.
 ```python
# diff
# 1.12.2 (protocol 340)
# 1.13 (protocol 393)
desired = ['1.13', 340]
versions = [vsn for vsn in versions if any(map(lambda each: each in vsn, desired))]
```
with the current command line extraction it might become a bit tricky to extract the desired protocols.

WDYT?

**Comment by joodicator** [comment]
Implementing this requires a bit more than just changing `versions`, as you suggest, because at the time of your post the `changed` attribute of each version-packet was fixed relative to the immediately previous version, and wouldn't be valid if there arbitrary gaps present.

However, I took the opportunity while doing some other reorganisation to update `matrix_html()` to dynamically calculate whether each version-packet has changed, relative to the previous version in an arbitrary given list, and added command-line options to set this list of displayed versions. This is documented in the output of `main.py --help`:
```
Usage: main.py [-h|--help] [-p|--pycraft-only] [VERSIONS...] [RFLAGS...]

[...]

VERSIONS: to restrict the displayed Minecraft versions to a subset of those,
available, version names or protocol numbers, or ranges of the form START..END,
may be given on the command line. E.g. "main.py 1.12.2 1.13" shows only the
difference between releases 1.12.2 and 1.13; and "main.py 315..340" shows all
versions with protocol numbers between 315 and 340, inclusive.
```

**Comment by TheSnoozer** [comment]
Damn, this looks so nice and is exactly what I thought about.

Thanks for doing this and adding tons of documentation so its clear what is possible and what can be done with it :-)
